INSERT INTO games (id, name, price, logo_url, image_url, tags, release_ts, developer, publisher, description, in_cart) 
VALUES 
(1, 'Counter-Strike 2', 300.0, 'https://cdn.cloudflare.steamstatic.com/steam/apps/730/capsule_184x69.jpg?t=1698860631', 'https://cdn.cloudflare.steamstatic.com/steam/apps/730/header.jpg?t=1698860631', 'Шутер,Экшен,Тактика,Для нескольких игроков', 15573, 'Valve', 'Valve', 'Более двух десятилетий Counter-Strike служит примером первоклассной соревновательной игры, путь развития которой определяют миллионы игроков со всего мира. Теперь пришло время нового этапа — Counter-Strike 2.', 1),
(2, 'Dota 2', 300.0, 'https://cdn.cloudflare.steamstatic.com/steam/apps/570/capsule_184x69.jpg?t=1701826869', 'https://cdn.cloudflare.steamstatic.com/steam/apps/570/header.jpg?t=1701826869', 'MOBA,Стратегия,Для нескольких игроков', 15895, 'Valve', 'Valve', 'Ежедневно миллионы игроков по всему миру сражаются от лица одного из более сотни героев Dota 2, и даже после тысячи часов в ней есть чему научиться. Благодаря регулярным обновлениям игра живёт своей жизнью: геймплей, возможности и герои постоянно преображаются.', 1),
(3, 'Warhammer 40,000: Rogue Trader', 1599.0, 'https://cdn.cloudflare.steamstatic.com/steam/apps/2186680/capsule_184x69.jpg?t=1702000678', 'https://cdn.cloudflare.steamstatic.com/steam/apps/2186680/header.jpg?t=1702000678', 'Изометрия,Исследования,Бой,Космос', 19698, 'Owlcat Games', 'Owlcat Games', 'Начните свое путешествие в первой cRPG в мрачной вселенной 41-го тысячелетия. Станьте Вольным Торговцем - наследником древней династии дерзких каперов, правящих собственной торговой империей и исследующих границы Империума с благословения Бога-Императора Человечества.', 0),
(4, 'Baldur''s Gate 3', 1999.0, 'https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/capsule_184x69.jpg?t=1702007647', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/header.jpg?t=1702007647', 'Ролевая игра,Решения с последствиями,Глубокий сюжет', 15573, 'Larian Studios', 'Larian Studios', 'Соберите отряд и вернитесь в Забытые Королевства. Вас ждет история о дружбе и предательстве, выживании и самопожертвовании, о сладком зове абсолютной власти.', 0),
(5, 'Rust', 1100.0, 'https://cdn.cloudflare.steamstatic.com/steam/apps/252490/capsule_184x69.jpg?t=1701938429', 'https://cdn.cloudflare.steamstatic.com/steam/apps/252490/header.jpg?t=1701938429', 'Выживание,Крафтинг,Для нескольких игроков,Открытый мир', 15573, 'Facepunch Studios', 'Facepunch Studios', 'The only aim in Rust is to survive. Everything wants you to die - the island’s wildlife and other inhabitants, the environment, other survivors. Do whatever it takes to last another night.', 0),
(6, 'PUBG: BATTLEGROUNDS', 300.0, 'https://cdn.cloudflare.steamstatic.com/steam/apps/578080/capsule_184x69.jpg?t=1701911655', 'https://cdn.cloudflare.steamstatic.com/steam/apps/578080/header.jpg?t=1701911655', 'Выживание,Шутер,Королевская битва,Для нескольких игроков', 15573, 'KRAFTON, Inc.', 'KRAFTON, Inc.', 'Играйте В PUBG: BATTLEGROUNDS бесплатно. Высаживайтесь в стратегически важных местах, добывайте оружие и припасы и постарайтесь выжить и остаться последней командой на одном из многочисленных полей боя.', 0),
(7, 'Hunt: Showdown', 472.15, 'https://cdn.cloudflare.steamstatic.com/steam/apps/594650/capsule_184x69.jpg?t=1702049226', 'https://cdn.cloudflare.steamstatic.com/steam/apps/594650/header.jpg?t=1702049226', 'Открытый мир,Шутер с эвакуацией,Атмосферная,Тактика', 15573, 'Crytek', 'Crytek', 'Hunt: Showdown — это захватывающий PvPvE-шутер от первого лица, в котором побеждают те, кто готов рисковать. Откройте охоту на чудовищ американских болот и получите заслуженную награду — славу, снаряжение и золото.', 0),
(8, 'Path of Exile', 300.0, 'https://cdn.cloudflare.steamstatic.com/steam/apps/238960/capsule_184x69.jpg?t=1701647105', 'https://cdn.cloudflare.steamstatic.com/steam/apps/238960/header.jpg?t=1701647105', 'Тёмное фэнтези,Ролевой экшен,Слэшер', 15573, 'Grinding Gear Games', 'Grinding Gear Games', 'Вы - изгнанник, который пытается выжить в мрачном мире Рэкласта. Сражаясь за свою жизнь, вы пытаетесь отомстить тем, кто обрёк вас на эту участь. Path of Exile создана игроками для игроков. Это онлайн Action RPG в тёмном фэнтэзийном мире.', 0),
(9, 'Euro Truck Simulator 2', 312.25, 'https://cdn.cloudflare.steamstatic.com/steam/apps/227300/capsule_184x69.jpg?t=1700739799', 'https://cdn.cloudflare.steamstatic.com/steam/apps/227300/header.jpg?t=1700739799', 'Вождение,Транспорт,Симулятор,Открытый мир', 15573, 'SCS Software', 'SCS Software', 'Станьте королем европейских дорог — водителем грузовика, который доставляет важные грузы на немалые расстояния! Вас ждут десятки городов Великобритании, Бельгии, Германии, Италии, Нидерландов, Польши и не только. Испытайте свои умения, выносливость и скорость.', 0),
(10, 'Against the Storm', 649.0, 'https://cdn.cloudflare.steamstatic.com/steam/apps/1336490/capsule_184x69_russian.jpg?t=1702199006', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1336490/header_russian.jpg?t=1702218649', 'Стратегия,Строительство базы,Симулятор,Градостроение', 19699, 'Eremite Games', 'Hooded Horse', 'Возродите цивилизацию и спасите ее от смертоносных дождей в градостроительном симуляторе в мире темного фэнтези. В роли наместника королевы возглавьте людей, бобров, ящеров, лис и гарпий и подчините себе природу.', 0);